# Generated by Django 5.2.5 on 2025-09-15 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieID', models.CharField(max_length=20, unique=True)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=120)),
                ('Actor2Name', models.CharField(blank=True, max_length=120)),
                ('DirectorName', models.CharField(max_length=120)),
                ('MovieGenre', models.CharField(choices=[('COMEDY', 'Comedy'), ('ROMANCE', 'Romance'), ('ACTION', 'Action'), ('DRAMA', 'Drama'), ('SCIFI', 'Sci-Fi'), ('HORROR', 'Horror'), ('THRILLER', 'Thriller'), ('ANIMATION', 'Animation'), ('OTHER', 'Other')], max_length=20)),
                ('ReleaseYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2027)])),
            ],
            options={
                'ordering': ['MovieTitle'],
            },
        ),
    ]
